# Generated by Django 6.0.5 on 2026-05-28 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enrollments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseenrollment',
            name='external_order_id',
            field=models.CharField(blank=True, db_index=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='courseenrollment',
            name='source',
            field=models.CharField(blank=True, default='', max_length=32),
        ),
    ]
