# Generated by Django 6.0.5 on 2026-08-11 13:39

import django.db.models.deletion
import enrollments.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0019_course_certificate_enabled_course_certificate_hours'),
        ('enrollments', '0002_courseenrollment_external_order_id_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(default=enrollments.models._gen_certificate_code, editable=False, max_length=12, unique=True)),
                ('student_name', models.CharField(max_length=155)),
                ('student_cpf', models.CharField(max_length=11)),
                ('hours', models.PositiveIntegerField(blank=True, null=True)),
                ('issued_at', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificates', to='courses.course')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('user', 'course'), name='uniq_certificate_user_course')],
            },
        ),
    ]
