# Generated by Django 6.0.5 on 2026-05-27 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_lesson_duration_seconds'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='category',
            field=models.CharField(choices=[('sales', 'Vendas e Negociação'), ('marketing', 'Marketing'), ('strategy', 'Estratégia Digital'), ('tool', 'Ferramenta(s)'), ('customer', 'Customer Success'), ('lifestyle', 'Estilo de Vida'), ('development', 'Desenvolvimento')], max_length=155),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='is_published',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='order',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='module',
            name='is_published',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='module',
            name='order',
            field=models.IntegerField(default=0),
        ),
    ]
