# Generated by Django 6.0.5 on 2026-05-27 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_alter_course_category_alter_lesson_is_published_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lessonattachment',
            name='file_url',
            field=models.FileField(upload_to='attachments/'),
        ),
    ]
