# Generated by Django 6.0.5 on 2026-05-28 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_lessoncomment'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='access_days',
            field=models.PositiveIntegerField(blank=True, help_text='Dias de acesso após matrícula. Vazio = vitalício', null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='kiwify_product_id',
            field=models.CharField(blank=True, db_index=True, default='', max_length=64),
        ),
    ]
