# Generated by Django 6.0.5 on 2026-06-29 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0008_courseform_formresponse'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formresponse',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
