# Generated by Django 6.0.5 on 2026-07-27 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0012_lesson_kind_lesson_questions_quizattempt'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='quiz_webhook_url',
            field=models.URLField(blank=True, default='', help_text='POST disparado ao aluno concluir um exercício deste curso. Vazio = desligado', max_length=500),
        ),
        migrations.AddField(
            model_name='lesson',
            name='allow_retake',
            field=models.BooleanField(default=True, help_text='Exercício: permitir refazer. Desligado = 1 tentativa'),
        ),
        migrations.AddField(
            model_name='module',
            name='requires_previous',
            field=models.BooleanField(default=False, help_text='Trava até todas as aulas dos módulos anteriores estarem concluídas'),
        ),
    ]
