# Generated by Django 6.0.5 on 2026-07-28 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0013_course_quiz_webhook_url_lesson_allow_retake_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='time_limit_seconds',
            field=models.PositiveIntegerField(default=0, help_text='Exercício: tempo em segundos. 0 = sem tempo'),
        ),
        migrations.AddField(
            model_name='quizattempt',
            name='attempts',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='quizattempt',
            name='started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='quizattempt',
            name='submitted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='quizattempt',
            name='timed_out',
            field=models.BooleanField(default=False),
        ),
    ]
