# Generated by Django 6.0.5 on 2026-07-28 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0014_lesson_time_limit_seconds_quizattempt_attempts_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='is_free',
            field=models.BooleanField(default=False, help_text='Curso gratuito: libera cadastro pela LP pública /lp/<slug>'),
        ),
        migrations.AddField(
            model_name='course',
            name='slug',
            field=models.SlugField(blank=True, help_text='URL da LP pública (/lp/<slug>). Só usado se is_free', max_length=160, null=True, unique=True),
        ),
    ]
