# Generated by Django 6.0.5 on 2026-07-28 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0015_course_is_free_course_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='lp_template',
            field=models.CharField(blank=True, default='', help_text="Layout da LP: '' = padrão, 'closer' = pré-qualificação Closer", max_length=32),
        ),
    ]
