# Generated by Django 6.0.5 on 2026-07-28 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0016_course_lp_template'),
    ]

    operations = [
        migrations.AddField(
            model_name='lessoncomment',
            name='resolved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
