# Generated by Django 6.0.5 on 2026-07-28 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0017_lessoncomment_resolved_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='comments_enabled',
            field=models.BooleanField(default=True, help_text='Alunos podem comentar nas aulas deste curso'),
        ),
    ]
