# Generated by Django 6.0.5 on 2026-08-11 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0018_course_comments_enabled'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='certificate_enabled',
            field=models.BooleanField(default=False, help_text='Emite certificado quando o aluno conclui 100% das aulas publicadas'),
        ),
        migrations.AddField(
            model_name='course',
            name='certificate_hours',
            field=models.PositiveIntegerField(blank=True, help_text='Carga horária impressa no certificado. Vazio = soma da duração das aulas', null=True),
        ),
    ]
